---
title: Naar een object glijden en terug
hero_image: images/banner.png
description: Naar een object glijden en terug
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Naar een object glijden en terug
