title: glide-to-object
hero_image: images/banner.png
description: glide-to-object description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
