---
title: Deslize para um objeto e volte
hero_image: images/banner.png
description: Deslize para um objeto e volte
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Deslize para um objeto e volte
