---
title: Desplázate hacia un objeto y regresa
hero_image: images/banner.png
description: Desplázate hacia un objeto y regresa
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Desplázate hacia un objeto y regresa
