---
title: Desplazarse hacia un objeto y regresar
hero_image: images/banner.png
description: Desplazarse hacia un objeto y regresar
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Desplazarse hacia un objeto y regresar
