---
title: Glisser vers un objet et revenir
hero_image: images/banner.png
description: Glisser vers un objet et revenir
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Glisser vers un objet et revenir
